### ISSUE TITLE
filter deleted objects 

### ISSUE THREAD

**Issue by quocvu** [dsanel/mongoose-delete#1]
Is there any shortcut to exclude soft-deleted objects from being part of selected results?

**Comment by markstos** [comment]
Isn't there a mistake in the "Usage" case, since the `find` method is called, not the `findNotDeleted` that was defined above? 

It seems that for soft deletes to work well, ignoring the deleted rows needs to be the *default* behavior, not requiring you to remember to call `findNotDeleted` for nearly every query. 

It seems instead that the behavior of the `find` method itself should be redefined, while a new method is added called `findWithDeleted`, that allows you to include the deleted rows if you specifically ask for them.
