### ISSUE TITLE
findDeleted error

### ISSUE THREAD

**Issue by johnH872** [dsanel/mongoose-delete#136]
When I use findDeleted, I found all records instead of records with deleted = true

**Comment by Luanardo** [comment]
Look like findDeleted return all records except records that has deleted = false. So when I used restore, it removed field deleted. After that, the record I restored still be found by findDeleted.

**Comment by vinhhathai** [comment]
same with me, when I used restore, the field 'deleted' was removed  instead of being changed to 'false'."

**Comment by saman-waruka** [comment]
I found same as @vinhhathai.

**Comment by saman-waruka** [comment]
> same with me, when I used restore, the field 'deleted' was removed instead of being changed to 'false'."

I found the same.

**Comment by dsanel** [comment]
Because we are using this query to get all "deleted" documents ([here](https://github.com/dsanel/mongoose-delete/blob/master/index.js#L173)) this is expected behavior.
```
return Model[modelMethodName].apply(this, arguments).where('deleted').ne(false);
```
You can try to use `TestSchema.plugin(mongoose_delete, {overrideMethods: 'all', use$neOperator: false});` to get only `deleted===true` documents
