### ISSUE TITLE
{Unique: true} includes soft deleted values

### ISSUE THREAD

**Issue by meilechwieder** [dsanel/mongoose-delete#86]
If I soft delete something that has a unique name and then I add a new record with that same name, it throws an error that there is already such a name. Indeed there is such a name, but is there a way we can ignore all the deleted records when we check for unique?

I will also not be able to remove the name from sort deleted records if name is   a required field.

Any help?

**Comment by khaight** [comment]
👍

**Comment by olehs** [comment]
You can make your 'deleted' field to default false: `{default: false}`
and then make your unique 'name' index partial:
` { unique: true, partialFilterExpression: { deleted: false } }`

**Comment by ysantalla** [comment]
Not working for my.

**Comment by johnyzv** [comment]
> ` { unique: true, partialFilterExpression: { deleted: false } }`

I confirm this works (mongo 4.2.3, mongoose 5.9.7, mongoose-delete 0.5.2)
This is my code
```
SomeSchema.index(
  { name: 1 },
  {
    unique: true,
    partialFilterExpression: {
      deleted: { $eq: false },
    },
  }
);
```

I did a lot of debugging until I understand exactly how this works.

PS: On my scenario, `mongoose-delete` was added after I already had data in my collection, so my records did not have `deleted: false` in order to be indexed by the unique index, so i had to do `SomeModel.updateMany({ deleted: false })`. Maybe this helps someone landing on this.
Cheers

**Comment by DashBarkHuss** [comment]
>  so i had to do `SomeModel.updateMany({ deleted: false })`. 

For any one who wants to do it in the mongo shell:
```bash
  db.somecollection.updateMany(
    { $or: [{ deleted: { $exists: false } }, { deleted: null }] },
    { $set: { deleted: false } }
  )
```

**Comment by dsanel** [comment]
Really interesting edge case and solution. It is not 100% related to the plugin, because we are using a unique index from MongoDB...
Maybe, only maybe, if we add some extra random prefix or suffix to the problematic field before we delete it, it can solve the problem.
